CC = gcc
LFLAGS =
CFLAGS =
LIBS =
INCLUDES =
LDIR =
TARGET = syx2rom
SOURCES = syx2rom.c

.PHONY: all

default: all

all:
	$(CC) $(CFLAGS) $(LFLAGS) $(INCLUDES) $(LIBS) -o $(TARGET) $(SOURCES) 

clean:
	rm $(TARGET)

